[project]
name = "botasaurus-web-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "botasaurus>=4.0.97",
    "mcp[cli]>=1.25.0",
    "ddgs>=9.10.0",
]
